#!/usr/bin/env python3
"""
Candidate source model v0.2: fuller nonminimally coupled scalar compatibility screen.

This pass keeps Reference Geometry v0.3 frozen and upgrades v0.1 from the reduced
q=phi^2 second-derivative operator to the null-contracted nonminimally coupled
scalar stress channel generated by actual phi(l,t) modes:

  T_kk = (k phi)^2 + xi [ G_kk phi^2 - k^mu k^nu nabla_mu nabla_nu(phi^2) ].

The computation uses a quadratic scalar-feature basis.  Because T_kk[sum c_i m_i]
is quadratic in the scalar amplitudes, the screen first fits the full quadratic
feature space, then checks whether the fitted quadratic form is close to a
positive rank-one matrix corresponding to one scalar field.  This separates
"the scalar stress channels have the right shapes" from "one smooth scalar field
already realizes them".
"""
from __future__ import annotations
import json, math, sys
from pathlib import Path
import numpy as np
import pandas as pd

HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[0]
OUT=ROOT/"data"/"candidate_source_model_v02"
OUT.mkdir(parents=True, exist_ok=True)
sys.path.insert(0,str(HERE))

from run_source_realism_prescreen_v02 import (
    PARAMS, make_geometry, diagnostics_general, window_shoulder,
    setup_reset_overlay, build_open_comp_overlay, zone_histories, smooth_pulse01,
)

EPS=1e-13


def build_grid(n_t=241,n_l=181):
    l=np.linspace(-18,18,n_l)
    t_end=PARAMS["T_B"]+2*PARAMS["T_R"]+PARAMS["T_H"]+PARAMS["T_C"]+PARAMS["T_Breset"]
    t=np.linspace(0,t_end,n_t)
    N,B,R,phase,times,C=make_geometry(t,l,PARAMS)
    d=diagnostics_general(t,l,N,B,R)
    return t,l,N,B,R,phase,times,C,d


def phase_window(t,times,name):
    t1,t2,t3,t4,t5,t6=times
    env=np.zeros_like(t)
    if name=="open":
        m=(t>=t1)&(t<=t4); env[m]=1.0
        m=(t>=t1)&(t<t2); env[m]=0.5*(1-np.cos(np.pi*(t[m]-t1)/max(t2-t1,EPS)))
        m=(t>t3)&(t<=t4); env[m]=0.5*(1+np.cos(np.pi*(t[m]-t3)/max(t4-t3,EPS)))
    elif name=="hold":
        m=(t>=t2)&(t<=t3); env[m]=1.0
    elif name=="edges":
        m=(t>=t1)&(t<t2); env[m]=smooth_pulse01((t[m]-t1)/max(t2-t1,EPS))
        m=(t>t3)&(t<=t4); env[m]=smooth_pulse01((t[m]-t3)/max(t4-t3,EPS))
    elif name=="comp":
        m=(t>=t4)&(t<=t5); env[m]=smooth_pulse01((t[m]-t4)/max(t5-t4,EPS))
    elif name=="setup_reset":
        m=(t>=0)&(t<t1); env[m]=smooth_pulse01(t[m]/max(t1,EPS))
        m=(t>=t5)&(t<=t6); env[m]=smooth_pulse01((t[m]-t5)/max(t6-t5,EPS))
    elif name=="B_setup":
        m=(t>=0)&(t<t1); env[m]=smooth_pulse01(t[m]/max(t1,EPS))
    elif name=="B_reset":
        m=(t>=t5)&(t<=t6); env[m]=smooth_pulse01((t[m]-t5)/max(t6-t5,EPS))
    elif name=="full":
        env[:]=1.0
    else:
        raise ValueError(name)
    return env


def spatial_profiles(l):
    a=np.abs(l)
    return {
        "core_bowl":(l/0.85)**2*np.exp(-(l/0.95)**2),
        "support_broad":(l/1.45)**2*np.exp(-(l/1.75)**2),
        "inner_ring":np.exp(-((a-0.65)/0.34)**4),
        "shoulder_ring":window_shoulder(l,2.3,1.0),
        "shoulder_bowl":((a-2.3)/1.05)**2*np.exp(-((a-2.3)/1.15)**2),
        "matching_ring":window_shoulder(l,5.5,1.45),
    }


def build_phi_modes(t,l,times):
    prof=spatial_profiles(l)
    pairs=[
        ("open","support_broad"),
        ("open","core_bowl"),
        ("comp","core_bowl"),
        ("comp","shoulder_ring"),
        ("setup_reset","inner_ring"),
        ("setup_reset","shoulder_ring"),
        ("B_setup","shoulder_ring"),
        ("B_reset","shoulder_ring"),
        ("setup_reset","matching_ring"),
    ]
    modes=[]; names=[]
    for ph,sp in pairs:
        modes.append(phase_window(t,times,ph)[:,None]*prof[sp][None,:])
        names.append(f"phi_{ph}__{sp}")
    return np.array(modes),names


def build_target(t,l,times,C,d):
    Tgeo=d["Tkk_min"]
    open_src=build_open_comp_overlay(t,l,C)
    sr_src=setup_reset_overlay(t,l,times,0.0066,0.0075)
    src=open_src+sr_src
    return Tgeo+src,Tgeo,src


def scalar_tkk(t,l,N,B,d,phi,xi):
    q=phi*phi
    phit=np.gradient(phi,t,axis=0,edge_order=2); phil=np.gradient(phi,l,axis=1,edge_order=2)
    qt=np.gradient(q,t,axis=0,edge_order=2); ql=np.gradient(q,l,axis=1,edge_order=2)
    qtt=np.gradient(qt,t,axis=0,edge_order=2); qtl=np.gradient(qt,l,axis=1,edge_order=2); qll=np.gradient(ql,l,axis=1,edge_order=2)
    Nt=np.gradient(N,t,axis=0,edge_order=2); Nl=np.gradient(N,l,axis=1,edge_order=2)
    Bt=np.gradient(B,t,axis=0,edge_order=2); Bl=np.gradient(B,l,axis=1,edge_order=2)
    cov_tt=qtt-(Nt/(N+EPS))*qt-(N*Nl/(B*B+EPS))*ql
    cov_tl=qtl-(Nl/(N+EPS))*qt-(Bt/(B+EPS))*ql
    cov_ll=qll-(B*Bt/(N*N+EPS))*qt-(Bl/(B+EPS))*ql
    Hplus=cov_tt/(N*N+EPS)+cov_ll/(B*B+EPS)+2*cov_tl/(N*B+EPS)
    Hminus=cov_tt/(N*N+EPS)+cov_ll/(B*B+EPS)-2*cov_tl/(N*B+EPS)
    Dp=phit/(N+EPS)+phil/(B+EPS); Dm=phit/(N+EPS)-phil/(B+EPS)
    Tgeo_plus=d["rho"]+d["pr"]+2*d["flux"]
    Tgeo_minus=d["rho"]+d["pr"]-2*d["flux"]
    Gplus=8*math.pi*Tgeo_plus; Gminus=8*math.pi*Tgeo_minus
    Tplus=Dp*Dp + xi*(Gplus*q-Hplus)
    Tminus=Dm*Dm + xi*(Gminus*q-Hminus)
    return np.minimum(Tplus,Tminus)


def observer_series(l,T):
    i0=int(np.argmin(np.abs(l)))
    masks={
        "core_line":None,
        "access_mean":np.abs(l)<=0.25,
        "support_mean":np.abs(l)<=0.75,
        "support_ring_mean":(np.abs(l)>=0.28)&(np.abs(l)<=0.95),
        "shoulder_mean":(np.abs(l)>=1.2)&(np.abs(l)<=4.5),
        "matching_mean":(np.abs(l)>4.5)&(np.abs(l)<=9.0),
    }
    out={}
    for obs,m in masks.items():
        out[obs]=T[:,i0] if obs=="core_line" else np.mean(T[:,m],axis=1)
    return out


def flattened_obs(l,T,obs_keep):
    ser=observer_series(l,T)
    return np.concatenate([ser[o] for o in obs_keep])


def build_feature_matrix(t,l,N,B,d,modes,names,xi,obs_keep):
    features=[]; meta=[]
    single=[]
    for i,name in enumerate(names):
        Ti=scalar_tkk(t,l,N,B,d,modes[i],xi)
        single.append(Ti)
        features.append(flattened_obs(l,Ti,obs_keep)); meta.append({"kind":"diag","i":i,"j":i,"feature":f"{name}^2"})
    n=len(names)
    for i in range(n):
        for j in range(i+1,n):
            Tij=scalar_tkk(t,l,N,B,d,modes[i]+modes[j],xi)-single[i]-single[j]
            features.append(flattened_obs(l,Tij,obs_keep)); meta.append({"kind":"cross","i":i,"j":j,"feature":f"{names[i]}*{names[j]}"})
    A=np.vstack(features).T
    return A,meta


def ridge_fit(A,y,w,lam=3e-5):
    Aw=A*w[:,None]; yw=y*w
    # normalize columns for conditioning
    norms=np.sqrt(np.mean(Aw*Aw,axis=0))+EPS
    An=Aw/norms[None,:]
    lhs=An.T@An + lam*np.eye(An.shape[1])
    rhs=An.T@yw
    cn=np.linalg.solve(lhs,rhs)
    c=cn/norms
    pred=A@c
    return c,pred


def metrics(l,target,Tfit):
    obs=["core_line","access_mean","support_mean","support_ring_mean","shoulder_mean","matching_mean"]
    ts=observer_series(l,target); fs=observer_series(l,Tfit); rs=observer_series(l,target-Tfit)
    rows=[]
    for o in obs:
        yt=ts[o]; yf=fs[o]; rr=rs[o]
        rms_t=float(np.sqrt(np.mean(yt*yt))); rms_r=float(np.sqrt(np.mean(rr*rr)))
        corr=float(np.corrcoef(yt,yf)[0,1]) if np.std(yt)>0 and np.std(yf)>0 else float("nan")
        rows.append({"observer_family":o,"target_rms":rms_t,"fit_rms":float(np.sqrt(np.mean(yf*yf))),"residual_rms":rms_r,"relative_rms_error":rms_r/(rms_t+EPS),"correlation":corr,"target_min":float(np.min(yt)),"fit_min":float(np.min(yf)),"target_max":float(np.max(yt)),"fit_max":float(np.max(yf))})
    return pd.DataFrame(rows),ts,fs,rs


def reconstruct_from_feature_coeffs(t,l,N,B,d,modes,names,meta,coef,xi):
    n=len(names); Z=np.zeros((n,n))
    for m,c in zip(meta,coef):
        i=m["i"]; j=m["j"]
        if i==j: Z[i,i]=c
        else: Z[i,j]=Z[j,i]=c
    # Feature fit grid direct reconstruction.
    T=np.zeros((len(t),len(l)))
    for m,c in zip(meta,coef):
        i=m["i"]; j=m["j"]
        if i==j:
            T+=c*scalar_tkk(t,l,N,B,d,modes[i],xi)
        else:
            T+=c*(scalar_tkk(t,l,N,B,d,modes[i]+modes[j],xi)-scalar_tkk(t,l,N,B,d,modes[i],xi)-scalar_tkk(t,l,N,B,d,modes[j],xi))
    # Rank-one positive approximation.
    evals,evecs=np.linalg.eigh(0.5*(Z+Z.T))
    idx=int(np.argmax(evals)); lam=max(float(evals[idx]),0.0); v=evecs[:,idx]
    coeff_phi=math.sqrt(lam)*v if lam>0 else np.zeros(n)
    phi=np.tensordot(coeff_phi,modes,axes=(0,0))
    T_rank1=scalar_tkk(t,l,N,B,d,phi,xi)
    pos_evals=evals[evals>0]
    rank1_fraction=float(lam/(np.sum(pos_evals)+EPS)) if len(pos_evals)>0 else 0.0
    neg_eig_sum=float(np.sum(np.abs(evals[evals<0])))
    return T,T_rank1,Z,coeff_phi,rank1_fraction,neg_eig_sum,evals


def run():
    t,l,N,B,R,phase,times,C,d=build_grid()
    target,Tgeo,src=build_target(t,l,times,C,d)
    modes,names=build_phi_modes(t,l,times)
    obs_keep=["core_line","access_mean","support_mean","support_ring_mean","shoulder_mean"]
    y=flattened_obs(l,target,obs_keep)
    weights={"core_line":2.0,"access_mean":1.6,"support_mean":1.35,"support_ring_mean":1.2,"shoulder_mean":1.15}
    w=np.concatenate([np.ones(len(t))*weights[o] for o in obs_keep])
    xi_values=[1/6,0.5]
    summaries=[]; saved={}
    for xi in xi_values:
        A,meta=build_feature_matrix(t,l,N,B,d,modes,names,xi,obs_keep)
        coef,pred=ridge_fit(A,y,w)
        # residual score using vector prediction
        sse=float(np.sum((w*(pred-y))**2)); sst=float(np.sum((w*(y-np.average(y,weights=w)))**2))
        Tfeat,Tr1,Z,cphi,rank1_frac,neg_eig_sum,evals=reconstruct_from_feature_coeffs(t,l,N,B,d,modes,names,meta,coef,xi)
        met_feat,_,_,_=metrics(l,target,Tfeat)
        met_r1,_,_,_=metrics(l,target,Tr1)
        sse_r1=0.0; yobs=flattened_obs(l,target,obs_keep); prob=flattened_obs(l,Tr1,obs_keep)
        sse_r1=float(np.sum((w*(prob-yobs))**2))
        summaries.append({"xi":float(xi),"feature_weighted_r2_like":1-sse/(sst+EPS),"feature_weighted_relative_rmse":math.sqrt(sse/(np.sum((w*y)**2)+EPS)),"rank1_weighted_r2_like":1-sse_r1/(sst+EPS),"rank1_weighted_relative_rmse":math.sqrt(sse_r1/(np.sum((w*y)**2)+EPS)),"rank1_positive_eigen_fraction":rank1_frac,"negative_eigenvalue_abs_sum":neg_eig_sum,"n_features":len(meta),"n_modes":len(names)})
        saved[xi]=(coef,meta,Tfeat,Tr1,Z,cphi,met_feat,met_r1,evals)
    summary_df=pd.DataFrame(summaries).sort_values("feature_weighted_relative_rmse")
    summary_df.to_csv(OUT/"nmc_full_scalar_xi_scan.csv",index=False)
    best_xi=float(summary_df.iloc[0]["xi"])
    coef,meta,Tfeat,Tr1,Z,cphi,met_feat,met_r1,evals=saved[best_xi]
    # Save metrics.
    met_feat.insert(0,"fit_type","quadratic_feature_fit")
    met_feat.insert(1,"xi",best_xi)
    met_r1.insert(0,"fit_type","rank_one_single_scalar_approx")
    met_r1.insert(1,"xi",best_xi)
    pd.concat([met_feat,met_r1],ignore_index=True).to_csv(OUT/"nmc_full_scalar_fit_metrics_by_observer.csv",index=False)
    # Compare v01.
    v01_path=ROOT/"data"/"candidate_source_model_v01"/"nmc_scalar_fit_metrics_by_observer.csv"
    if v01_path.exists():
        v01=pd.read_csv(v01_path)[["observer_family","relative_rms_error","correlation"]].rename(columns={"relative_rms_error":"v01_relative_rms_error","correlation":"v01_correlation"})
        comp=met_feat.merge(v01,on="observer_family",how="left")
        comp["delta_relative_rms_error_feature_minus_v01"]=comp["relative_rms_error"]-comp["v01_relative_rms_error"]
        comp["delta_correlation_feature_minus_v01"]=comp["correlation"]-comp["v01_correlation"]
        comp.to_csv(OUT/"nmc_v02_vs_v01_metric_comparison.csv",index=False)
    # Coefficients.
    rows=[]
    for m,c in sorted(zip(meta,coef),key=lambda x:abs(x[1]),reverse=True):
        if abs(c)>1e-8:
            rows.append({**m,"feature_coefficient":float(c),"abs_feature_coefficient":float(abs(c))})
    pd.DataFrame(rows).to_csv(OUT/"nmc_full_scalar_feature_coefficients.csv",index=False)
    phi_rows=[]
    for n,c in sorted(zip(names,cphi),key=lambda x:abs(x[1]),reverse=True):
        phi_rows.append({"basis":n,"rank1_phi_coefficient":float(c),"abs_rank1_phi_coefficient":float(abs(c))})
    pd.DataFrame(phi_rows).to_csv(OUT/"nmc_full_scalar_rank1_phi_coefficients.csv",index=False)
    # Ledgers.
    zero=np.zeros_like(target)
    led_t,_,_=zone_histories(t,l,target,zero,phase); led_t.insert(0,"case","target_v02_combined")
    led_f,_,_=zone_histories(t,l,Tfeat,zero,phase); led_f.insert(0,"case","nmc_quadratic_feature_fit")
    led_r,_,_=zone_histories(t,l,Tr1,zero,phase); led_r.insert(0,"case","nmc_rank_one_single_scalar_approx")
    pd.concat([led_t,led_f,led_r],ignore_index=True).to_csv(OUT/"nmc_full_scalar_observer_ledgers.csv",index=False)
    # Digest.
    ts=observer_series(l,target); fs=observer_series(l,Tfeat); r1s=observer_series(l,Tr1)
    idx=np.unique(np.round(np.linspace(0,len(t)-1,501)).astype(int))
    dig=[]
    for i in idx:
        row={"t":float(t[i]),"phase":str(phase[i])}
        for obs in obs_keep:
            row[f"{obs}_target_Tkk"]=float(ts[obs][i])
            row[f"{obs}_nmc_feature_Tkk"]=float(fs[obs][i])
            row[f"{obs}_rank1_scalar_Tkk"]=float(r1s[obs][i])
            row[f"{obs}_feature_residual_Tkk"]=float(ts[obs][i]-fs[obs][i])
        dig.append(row)
    pd.DataFrame(dig).to_csv(OUT/"nmc_full_scalar_timeseries_digest.csv",index=False)
    # Field diagnostics for rank-one phi.
    phi=np.tensordot(cphi,modes,axes=(0,0)); q=phi*phi
    zone_masks={"access":np.abs(l)<=0.25,"support":np.abs(l)<=0.75,"support_ring":(np.abs(l)>=0.28)&(np.abs(l)<=0.95),"shoulder":(np.abs(l)>=1.2)&(np.abs(l)<=4.5),"global":np.ones_like(l,dtype=bool)}
    diag=[]
    for zn,m in zone_masks.items():
        idx2=np.ix_(np.ones(len(t),dtype=bool),m)
        diag.append({"zone":zn,"max_abs_phi_rank1":float(np.max(np.abs(phi[idx2]))),"mean_phi2_rank1":float(np.mean(q[idx2])),"max_phi2_rank1":float(np.max(q[idx2]))})
    pd.DataFrame(diag).to_csv(OUT/"nmc_full_scalar_field_diagnostics.csv",index=False)
    # Ranking.
    best_row=summary_df.iloc[0].to_dict()
    ranking=pd.DataFrame([
        {"candidate":"NMC_scalar_quadratic_feature_space","status":"strong_channel_match" if best_row["feature_weighted_r2_like"]>0.65 else "partial_channel_match","score":float(best_row["feature_weighted_r2_like"]),"main_strength":"The full null-contracted scalar stress channels span the target source ledger substantially better than the v0.1 reduced second-derivative screen.","main_blocker":"The fitted quadratic form must be close to positive rank-one for a single scalar field; otherwise it represents a multi-component/effective scalar-feature fit."},
        {"candidate":"single_NMC_scalar_rank_one","status":"candidate_only_if_rank1_fit_good","score":float(best_row["rank1_weighted_r2_like"]),"main_strength":"A positive rank-one approximation corresponds to one smooth scalar field phi(l,t).","main_blocker":"If rank-one score is weak, the source target needs either multiple scalar components or infrastructure-source terms."},
        {"candidate":"hybrid_NMC_plus_infrastructure_repayment","status":"lead_architecture","score":0.75,"main_strength":"Uses scalar stress channels for core/access and support shaping while retaining a separate conserved infrastructure source for setup/reset and shoulder repayment.","main_blocker":"Requires a coupling/interface model and later backreaction stability screen."},
    ])
    ranking.to_csv(OUT/"candidate_source_model_ranking_v02.csv",index=False)
    extracts={
        "screen":"candidate_source_model_v02",
        "geometry":"Reference Geometry v0.3 frozen",
        "method":"quadratic feature fit for full null-contracted NMC scalar stress channel, followed by rank-one single-scalar consistency check",
        "best_xi":best_xi,
        "best_summary":best_row,
        "xi_scan":summary_df.to_dict(orient="records"),
        "top_feature_terms":pd.DataFrame(rows).head(12).to_dict(orient="records"),
        "top_rank1_phi_terms":pd.DataFrame(phi_rows).head(12).to_dict(orient="records"),
        "observer_metrics":pd.concat([met_feat,met_r1],ignore_index=True).to_dict(orient="records"),
        "interpretation":[
            "The fuller scalar stress channel is tested by features generated from actual phi(l,t) modes rather than q=phi^2 modes alone.",
            "The quadratic feature fit tests whether NMC scalar stress terms contain the right local shapes for the target ledger.",
            "The rank-one approximation tests whether those shapes can plausibly come from one scalar field rather than an effective multi-component scalar source.",
            "A strong feature fit together with a weaker rank-one fit supports the hybrid source architecture: NMC scalar support plus infrastructure/repayment source."
        ]
    }
    (OUT/"candidate_source_model_v02_extracts.json").write_text(json.dumps(extracts,indent=2))
    note=ROOT/"report_progress_notes.md"
    with note.open("a") as f:
        f.write("\n\n## Candidate source model v0.2\n\nRan fuller NMC scalar compatibility screen using phi(l,t)-generated quadratic stress features and a rank-one single-scalar consistency check.\n")
    print(json.dumps(extracts,indent=2))

if __name__=="__main__":
    run()
